shop/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('home/', ViewHome.as_view(), name='home'),
    path('following/', FollowingListView.as_view(), name='following_list'),
    path('follow/', user_follow, name='user_follow'),
    path('post/<int:id>/<slug:slug>/', product_detail, name='post-detail'),
    path('import_contacts_and_send_email/', import_contacts_and_send_email, name='import_contacts_and_send_email'),
    path('', ViewIndex.as_view(), name='index'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', user_login, name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', logout_user, name="logout"),
    path('csrf_failure/', csrf_failure, name='csrf_failure'),
    path('like/<int:material_id>/', like_material, name='like_material'),
    path('catalog/', ViewCatalog.as_view(), name='сatalog'),  # Путь для отображения каталога
    path('catalog/<str:url>/', filter_posts, name='filter_posts'),# Путь для фильтрации постов по категории
    path('search/', search_results, name='search_results'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/news/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', get_video, name='news'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include(('message.urls', 'message'), namespace='message')),
    path('provider/', include(('provider.urls', 'provider'), namespace='provider')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('main.urls', 'main'), namespace='main')),

]

shop/news/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

# Create your models here.
class Video(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='image/')
    file = models.FileField(
        upload_to='video/',
        validators=[FileExtensionValidator(allowed_extensions=['mp4'])]
    )
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

shop/news/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from .models import Video


# Create your views here.
class ViewNews(ListView):
    model = Video
    context_object_name = 'video_list'
    template_name = 'news/news.html'

def get_video(request, pk: int):
    _video = get_object_or_404(Video, id=pk)
    return render(request, "news/news.html", {"video": _video})


class BaseView(ListView):
    model = Video
    context_object_name = 'videos'
    template_name = 'news/base.html'

    def get_queryset(self):
        return Video.objects.all()

shop/news/templates/news/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

	<link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
	{% block css %}
    {% endblock %}

	<title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">
            <img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Stroev-Home
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:сatalog' %}">Catalog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:news' %}">News</a>
                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                {% if is_catalog_page %}
                <!-- Search form positioned to the right -->
                <li class="nav-item">
                    <form class="d-flex" action="{% url 'main:search_results' %}" method="GET">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                        <button class="btn btn-outline-dark" type="submit">Search</button>
                    </form>
                </li>
                {% endif %}
                <!-- End of search form positioning -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"><i class="far fa-user"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:login' %}">
                                        <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
                                        {{ user.username }}
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'main:profile' %}">
                                        <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
                                        {{ user.username }}
                                    </a>
                                </li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'main:login' %}">Авторизация клиента</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:register' %}">Регистрация клиента</a></li>
                            <li><a class="dropdown-item" href="{% url 'provider:register' %}">Регистрация поставщика</a></li>
                            <li><a class="dropdown-item" href="{% url 'provider:login' %}">Авторизация поставщика</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}

{% block catalog %}
{% endblock %}

{% block footer %}
{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>

</body>
</html>

shop/news/templates/news/news.html
{% extends "news/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'news/news.css' %}">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
{% endblock %}
{% block content %}
<div class="main-posts">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6">
          <img class="single-video" src="{{ video.image.url }}" alt="">
        </div>
        <div class="col-md-6 col-sm-6">
          <span class="date">{{ video.create_at }}</span>
          <h4><a href="{% url 'news:news' %}">{{ video.title }}</a></h4>
          <p>{{ video.description }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <video
              id="my-video"
              class="video-js"
              controls
              preload="auto"
              width="1000"
              height="800"
              data-setup="{}"
          >

          </video>
        </div>
      </div>
    </div>
  </div>
<svg preserveAspectRatio="xMidYMid slice" viewBox="10 10 80 80">
    <defs>
        <style>
            @keyframes rotate {
					 0% {
                    transform: rotate(0deg);
                }
                100% {
                    transform: rotate(360deg);
                }
            }
            .out-top {
                animation: rotate 20s linear infinite;
                transform-origin: 13px 25px;
            }
            .in-top {
                animation: rotate 10s linear infinite;
                transform-origin: 13px 25px;
            }
            .out-bottom {
                animation: rotate 25s linear infinite;
                transform-origin: 84px 93px;
            }
            .in-bottom {
                animation: rotate 15s linear infinite;
                transform-origin: 84px 93px;
            }
        </style>
    </defs>
    <path fill="#9b5de5" class="out-top" d="M37-5C25.1-14.7,5.7-19.1-9.2-10-28.5,1.8-32.7,31.1-19.8,49c15.5,21.5,52.6,22,67.2,2.3C59.4,35,53.7,8.5,37-5Z"/>
    <path fill="#f15bb5" class="in-top" d="M20.6,4.1C11.6,1.5-1.9,2.5-8,11.2-16.3,23.1-8.2,45.6,7.4,50S42.1,38.9,41,24.5C40.2,14.1,29.4,6.6,20.6,4.1Z"/>
    <path fill="#00bbf9" class="out-bottom" d="M105.9,48.6c-12.4-8.2-29.3-4.8-39.4.8-23.4,12.8-37.7,51.9-19.1,74.1s63.9,15.3,76-5.6c7.6-13.3,1.8-31.1-2.3-43.8C117.6,63.3,114.7,54.3,105.9,48.6Z"/>
    <path fill="#00f5d4" class="in-bottom" d="M102,67.1c-9.6-6.1-22-3.1-29.5,2-15.4,10.7-19.6,37.5-7.6,47.8s35.9,3.9,44.5-12.5C115.5,92.6,113.9,74.6,102,67.1Z"/>
</svg>
{% endblock content %}
{% block footer %}
    <footer>
        <div class="footer-content">
            <h3>Контакты</h3>
            <p>Телефон: +79206945165</p>
            <p>Email: bbd3372005@gmail.com</p>
            <p>Адрес: улица Трехсвятская д.14</p>
        </div>
        <div class="footer-content">
            <h3>Ссылки</h3>
            <ul>
                <li><a href="{% url 'main:index' %}">Главная</a></li>
                <li><a href="#">О нас</a></li>
                <li><a href="#">Контакты</a></li>
                <li><a href="#">Услуги</a></li>
            </ul>
        </div>
    </footer>
{% endblock %}