shop/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('home/', ViewHome.as_view(), name='home'),
    path('following/', FollowingListView.as_view(), name='following_list'),
    path('follow/', user_follow, name='user_follow'),
    path('post/<int:id>/<slug:slug>/', product_detail, name='post-detail'),
    path('import_contacts_and_send_email/', import_contacts_and_send_email, name='import_contacts_and_send_email'),
    path('', ViewIndex.as_view(), name='index'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', user_login, name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', logout_user, name="logout"),
    path('csrf_failure/', csrf_failure, name='csrf_failure'),
    path('like/<int:material_id>/', like_material, name='like_material'),
    path('catalog/', ViewCatalog.as_view(), name='сatalog'),  # Путь для отображения каталога
    path('catalog/<str:url>/', filter_posts, name='filter_posts'),# Путь для фильтрации постов по категории
    path('search/', search_results, name='search_results'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/message/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('dialogs/<int:member_from>/', DialogsView.as_view(), name='dialogs_view'),
    path('create_dialog/<int:id>/', create_dialog, name='create_dialog'),
    path('list_chats/', ListChatsView.as_view(), name='list_chats'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/orders/urls.py
from django.urls import path
from .views import *
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('my-orders/', UserOrderListView.as_view(), name='user_orders'),
]

shop/provider/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', BuildingMaterialsCreateView.as_view(), name='main'),

    path('delete_material/', delete_material, name='delete_material'),
    path('list_posts/', ListPosts.as_view(), name='list_posts'),
    path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('add_post/', BuildingMaterialsCreateView.as_view(), name='add'),
    path('register/', RegistrationProviderView.as_view(), name='register'),
    path('login/', user_login, name='login'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include(('message.urls', 'message'), namespace='message')),
    path('provider/', include(('provider.urls', 'provider'), namespace='provider')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('main.urls', 'main'), namespace='main')),

]

shop/main/models.py
import os
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse
from django.utils.text import slugify
from PIL import Image
from django.contrib.auth import get_user_model
# Импортируем наш пользовательский метод
from .utils import *
class User(AbstractUser):
    role = models.BooleanField(default=False)

    class Meta:
        swappable = 'AUTH_USER_MODEL'
        db_table = 'main_user'
class Contact(models.Model):
    user_from = models.ForeignKey('Profile', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('Profile', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user_from', 'user_to'),)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254, default='xxx@mail.com')
    image = models.ImageField(upload_to='profile_images', default='profile_pics/default.jpg')
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=255, null=True)
    postal_code = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=100, null=True)
    passport_number = models.CharField(max_length=6, null=True)
    passport_series = models.CharField(max_length=4, null=True)

    following = models.ManyToManyField('self', through='Contact', symmetrical=False, related_name='followers')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        default_image_path = os.path.join(settings.MEDIA_ROOT, 'profile_images', 'default.jpg')

        if os.path.exists(default_image_path):
            try:
                with Image.open(default_image_path) as img:
                    img.thumbnail((300, 300))
                    img.save(self.image.path)
            except FileNotFoundError:
                print(f"File not found: {default_image_path}")
        else:
            print(f"Default image not found: {default_image_path}")
class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название категории')
    description = models.TextField('Описание категории кратко ')
    url = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class BuildingMaterials(models.Model):
    title = models.CharField(max_length=128, null=True, verbose_name='Название материала')
    description = models.TextField(max_length=256, null=True, verbose_name='Описание материала')
    image = models.ImageField(default='chto.png', upload_to='profile_pics')
    price = models.IntegerField(null=True, default=0, verbose_name='Цена')
    slug = models.SlugField(unique=True, null=True)
    available = models.BooleanField(default=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    likes = models.ManyToManyField(Profile, related_name='liked_materials', through='Like')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='materials')
    views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('main:post-detail', args=[self.id, self.slug])

    def __str__(self):
        return self.title

class Review(models.Model):
    post = models.ForeignKey(BuildingMaterials, on_delete=models.CASCADE, related_name='reviews')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review by {self.author.username} on {self.post.title}'

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    material = models.ForeignKey(BuildingMaterials, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'material')

shop/provider/models.py
from django.db import models

# Create your models here.

shop/main/forms.py
from .models import *
from django import forms

from django.contrib.auth import get_user_model

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Review, User

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=150)
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        User = get_user_model()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This username is already taken.')
        return username

from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({
            'rows': 3,  # Установите желаемое количество строк
            'cols': 40,  # Установите желаемое количество столбцов
            'placeholder': 'Напишите ваш отзыв здесь...',  # Опционально: добавьте placeholder
            'class': 'form-control',  # Добавьте класс Bootstrap для стилизации
        })

shop/provider/forms.py
from django.contrib.auth import get_user_model

from .models import *
from django import forms
from django.contrib.auth.models import User
from main.models import BuildingMaterials
class RegistrationProviderForm(forms.Form):
    username = forms.CharField(label='Username', max_length=150)
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    first_name = forms.CharField(label='First Name', max_length=150)
    last_name = forms.CharField(label='Last Name', max_length=150)
    city = forms.CharField(label='City', max_length=25)
    passport_number = forms.CharField(label='Passport Number', max_length=6)
    passport_series = forms.CharField(label='Passport Series', max_length=4)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        User = get_user_model()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This username is already taken.')
        return username

class AddPostForm(forms.ModelForm):
    class Meta:
        model = BuildingMaterials
        fields = ['title', 'description', 'image', 'price', 'category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['price'].widget.attrs.update({'class': 'form-control'})

shop/provider/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.models import User
from django.core.checks import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView
from django.views.generic import ListView
from .forms import RegistrationProviderForm, AddPostForm
from main.models import Profile, BuildingMaterials, Category, Review


class RegistrationProviderView(View):
    form_class = RegistrationProviderForm
    template_name = 'provider/register.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            city = form.cleaned_data['city']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            passport_number = form.cleaned_data['passport_number']
            passport_series = form.cleaned_data['passport_series']

            # Отладочные сообщения
            print(f'Username: {username}')
            print(f'Email: {email}')
            print(f'Password: {password}')
            print(f'City: {city}')
            print(f'First Name: {first_name}')
            print(f'Last Name: {last_name}')
            print(f'Passport Number: {passport_number}')
            print(f'Passport Series: {passport_series}')
            User = get_user_model()
            user = User.objects.create_user(username=username, email=email, password=password, role=False)
            profile = Profile.objects.create(
                user=user,
                email=email,
                passport_series=passport_series,
                passport_number=passport_number,
                last_name=last_name,
                first_name=first_name,
                city=city
            )

            # Отладочные логи
            print(f'User: {user}')
            print(f'Profile: {profile}')

            if profile:
                print(f'Profile created successfully for {username}')

            return redirect('main:login')
        else:
            print('Form is invalid')
            print(form.errors)
            return render(request, self.template_name, {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.role == False:
                login(request, user)
                return redirect('provider:add')  # Перенаправление на нужную страницу для роли False
            else:
                # Роль True - перенаправляем на другую страницу
                return redirect('main:login')  # Замените 'main:some_other_page' на нужный URL
        else:
            # Пользователь с указанными учетными данными не найден, перезагрузка страницы
            return redirect('main:login')  # Перенаправление на ту же страницу в случае ошибки ввода
    else:
        return render(request, 'blog/login.html')

class BuildingMaterialsCreateView(CreateView):
    model = BuildingMaterials
    form_class = AddPostForm
    success_url = '/provider/list_posts/'
    template_name = 'provider/add.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()

        return context

    def form_valid(self, form):
        building_material = form.save(commit=False)
        building_material.author = self.request.user.profile
        building_material.category = form.cleaned_data['category']
        building_material.slug = slugify(f"{building_material.title}-{building_material.author.id}-{building_material.category.id}")
        building_material.save()
        return super().form_valid(form)

class PostDetailView(DetailView):
    model = BuildingMaterials
    template_name = 'provider/post_detail.html'
    context_object_name = 'product'

    def get_object(self, queryset=None):
        material_id = self.kwargs.get('pk')
        # Получаем BuildingMaterials по ID и проверяем, что он принадлежит текущему пользователю
        return get_object_or_404(BuildingMaterials, id=material_id, author=self.request.user.profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        if product:
            reviews = Review.objects.filter(post=product)
            paginator = Paginator(reviews, 4)
            page_number = self.request.GET.get('page')  # Получаем текущий номер страницы
            try:
                reviews = paginator.page(page_number)
            except PageNotAnInteger:
                reviews = paginator.page(1)  # Если номер страницы не является целым числом, возвращаем первую страницу
            except EmptyPage:
                reviews = paginator.page(paginator.num_pages)  # Если страница пуста, возвращаем последнюю страницу

            context['reviews'] = reviews
        return context


class ListPosts(ListView):
    model = BuildingMaterials
    template_name = 'provider/posts.html'
    context_object_name = 'materials'

    def get_queryset(self):
        # Возвращаем QuerySet объектов BuildingMaterials,
        # фильтрованных по пользователю, для отображения в ListView
        return BuildingMaterials.objects.filter(author=self.request.user.profile)
def delete_material(request):
    if request.method == 'POST':
        material_id = request.POST.get('material_id')
        material = get_object_or_404(BuildingMaterials, id=material_id)
        material.delete()

        return redirect(reverse('provider:list_posts'))  # Replace 'materials_list' with your actual view name
    return redirect(reverse('provider:list_posts'))

shop/provider/templates/provider/add.html
{% extends "provider/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/provider.css' %}">
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Добавь свою анкету</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_title">Название</label>
            {{ form.title }}
        </div>
        <div class="form-group mb-3">
            <label for="id_description">Описание</label>
            {{ form.description }}
        </div>
        <div class="form-group mb-3">
            <label for="id_image">Картинка</label>
            {{ form.image }}
        </div>
        <div class="form-group mb-3">
        <label for="id_category">Категория</label>
        <select class="form-select" id="id_category" name="category">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        </div>

        <div class="form-group mb-3">
            <label for="id_price">Цена</label>
            {{ form.price }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock content %}
{% block footer %}

{% endblock %}

shop/provider/templates/provider/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

	<link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
	{% block css %}
    {% endblock %}

	<title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">
            <img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Stroy-Dom
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:сatalog' %}">Каталог</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'message:list_chats' %}">Сообщения</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'provider:list_posts' %}">Ваши Анкеты</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'provider:add' %}">Добавить Анкету</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                {% if is_catalog_page %}
                <!-- Search form positioned to the right -->
                <li class="nav-item">
                    <form class="d-flex" action="{% url 'main:search_results' %}" method="GET">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                        <button class="btn btn-outline-dark" type="submit">Search</button>
                    </form>
                </li>
                {% endif %}
                <!-- End of search form positioning -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"><i class="far fa-user"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:login' %}">
                                        <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
                                        {{ user.username }}
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'main:profile' %}">
                                        <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
                                        {{ user.username }}
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">
                                        Подписчики {{ followers_count }}
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'main:following_list' %}">
                                        Подписки
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'orders:user_orders' %}">
                                        Заказы
                                    </a>
                                </li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'main:login' %}">Авторизация</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:register' %}">Регистрация</a></li>

                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}

{% block catalog %}
{% endblock %}

{% block footer %}
{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>

</body>
</html>

shop/provider/templates/provider/main.html
{% extends "news/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/provider.css' %}">
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Добавь свою анкету</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_title">Название</label>
            {{ form.title }}
        </div>
        <div class="form-group mb-3">
            <label for="id_description">Описание</label>
            {{ form.description }}
        </div>
        <div class="form-group mb-3">
            <label for="id_image">Картинка</label>
            {{ form.image }}
        </div>
        <div class="form-group mb-3">
        <label for="id_category">Категория</label>
        <select class="form-select" id="id_category" name="category">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        </div>

        <div class="form-group mb-3">
            <label for="id_price">Цена</label>
            {{ form.price }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock content %}
{% block footer %}
    <footer>
        <div class="footer-content">
            <h3>Контакты</h3>
            <p>Телефон: +79206945165</p>
            <p>Email: bbd3372005@gmail.com</p>
            <p>Адрес: улица Трехсвятская д.14</p>
        </div>
        <div class="footer-content">
            <h3>Ссылки</h3>
            <ul>
                <li><a href="{% url 'main:index' %}">Главная</a></li>
                <li><a href="#">О нас</a></li>
                <li><a href="#">Контакты</a></li>
                <li><a href="#">Услуги</a></li>
            </ul>
        </div>
    </footer>
{% endblock %}

shop/provider/templates/provider/posts.html
{% extends "provider/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/provider_list.css' %}">
{% endblock %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container">
    {% if materials %}
    <h2>Строительные Материалы:</h2>
    <div class="card-container">
        {% for material in materials %}
        <div class="product-card">
            <div class="product-thumb">
                <img src="{{ material.image.url }}" alt="{{ material.title }}">
            </div>
            <div class="product-details">
                <h4>{{ material.title }}</h4>
                <p>{{ material.description|truncatewords:20 }}</p>
                <p class="product-price">{{ material.price }} ₽</p>
                <div class="product-bottom-details">
                    <div class="product-links">
                        <a href="{% url 'provider:post_detail' material.id %}"><i class="fa fa-edit"></i></a>
                        <a href="#" class="delete-link" data-material-id="{{ material.id }}" data-toggle="modal" data-target="#deleteModal"><i class="fa fa-trash"></i></a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>У вас пока нет постов.</p>
    {% endif %}
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form method="POST" action="{% url 'provider:delete_material' %}">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Удалить материал</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Вы действительно хотите удалить этот материал?
          <input type="hidden" name="material_id" id="material_id" value="">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
          <button type="submit" class="btn btn-danger">Да</button>
        </div>
      </form>
    </div>
  </div>
</div>



<!-- Include jQuery and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script>
$(document).ready(function(){
    $('.delete-link').click(function(){
        var materialId = $(this).data('material-id');
        $('#material_id').val(materialId);
    });
});
</script>
{% endblock content %}

{% block footer %}
<!-- Вставьте код для футера здесь -->
{% endblock %}