shop/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('home/', ViewHome.as_view(), name='home'),
    path('following/', FollowingListView.as_view(), name='following_list'),
    path('follow/', user_follow, name='user_follow'),
    path('post/<int:id>/<slug:slug>/', product_detail, name='post-detail'),
    path('import_contacts_and_send_email/', import_contacts_and_send_email, name='import_contacts_and_send_email'),
    path('', ViewIndex.as_view(), name='index'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', user_login, name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', logout_user, name="logout"),
    path('csrf_failure/', csrf_failure, name='csrf_failure'),
    path('like/<int:material_id>/', like_material, name='like_material'),
    path('catalog/', ViewCatalog.as_view(), name='сatalog'),  # Путь для отображения каталога
    path('catalog/<str:url>/', filter_posts, name='filter_posts'),# Путь для фильтрации постов по категории
    path('search/', search_results, name='search_results'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/news/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', get_video, name='news'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/orders/urls.py
from django.urls import path
from .views import *
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('my-orders/', UserOrderListView.as_view(), name='user_orders'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include(('message.urls', 'message'), namespace='message')),
    path('provider/', include(('provider.urls', 'provider'), namespace='provider')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('main.urls', 'main'), namespace='main')),

]

shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from main.models import BuildingMaterials
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(BuildingMaterials, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        # Используйте метод add объекта cart, передавая экземпляр BuildingMaterials
        cart.add(product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

from django.http import JsonResponse

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(BuildingMaterials, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

shop/cart/templates/cart/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

	<link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
	{% block css %}
    {% endblock %}

	<title>Hello, world!</title>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">Stroev-Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:сatalog' %}">Catalog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:news' %}">News</a>
                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                {% if is_catalog_page %}
                <!-- Перемещение формы поиска вправо с помощью ms-auto -->
                <li class="nav-item">
                    <form class="d-flex" action="{% url 'main:search_results' %}" method="GET">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                        <!-- Изменение цвета кнопки Search на черный -->
                        <button class="btn btn-outline-dark" type="submit">Search</button>
                        <!-- Конец изменения цвета кнопки Search -->
                    </form>
                </li>
                {% endif %}
                <!-- Конец перемещения формы поиска -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"><i class="far fa-user"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:login' %}">
                                        <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
                                        {{ user.username }}
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a class="dropdown-item" href="#">
                                        <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
                                        {{ user.username }}
                                    </a>
                                </li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'main:login' %}">Авторизация</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

{% block catalog %}
{% endblock %}

{% block footer %}
{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>

</body>
</html>

shop/cart/templates/cart/cart_detail.html
{% extends "provider/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
{% endblock %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Ваша корзина</h1>
        <table class="cart">
            <thead>
                <tr>
                    <th>Картинка</th>
                    <th>Продукт</th>
                    <th>Количество</th>
                    <th>Удалить</th>
                    <th>Цена за один</th>
                    <th>Конечная цена</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
{% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="Product Image">
                                </a>
                            </td>
                            <td>{{ product.title }}</td>
                            <td>{{ item.quantity }}</td>
                            <td><a href="{% url 'cart:cart_remove' product.id %}" class="remove-btn">Удалить</a></td>
                            <td class="num">₽{{ item.price }}</td>
                            <td class="num">₽{{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Сумма</td>
                    <td colspan="4"></td>
                    <td class="num">₽{{ cart.get_total_price }}</td>
                </tr>
            </tbody>
        </table>
        <p class="text-right">
            <a href="{% url 'main:index' %}" class="button light">Продолжить покупки</a>
            <a href="{% url 'orders:order_create' %}" class="button">Оформить</a>
        </p>
    </div>
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            color: #ccc;
            background-color: #2b2b2b;
            margin: 0;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            padding-top: 60px; /* Отступ сверху для учета фиксированной навигационной панели */
        }
        .container {
            padding-top: 70px;
        }
        a {
            color: #ff7f50;
            text-decoration: none;
        }
        a:hover {
            color: #ffa07a;
            text-decoration: underline;
        }
        .navbar {
            background-color: #333;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
        }
        .navbar-light .navbar-nav .nav-link {
            color: #ccc;
            font-weight: 500;
            text-transform: uppercase;
        }
        .navbar-nav .dropdown-menu {
            right: 0;
            left: auto;
        }
        .top-menu li a::after {
            content: '';
            display: block;
            width: 100%;
            background-color: #ccc;
            height: 1px;
            transition: all .3s;
            transform: scale(0);
        }
        .top-menu li a:hover::after {
            transform: scale(1);
        }
        section {
            padding: 50px 0;
        }
        h1 {
            text-align: center;
            margin-bottom: 30px;
            font-size: 2.5em;
            color: #111;
        }
        .cart {
            width: 90%;
            max-width: 1000px;
            margin: 100px auto 0 auto;
            border-collapse: collapse;
            background: rgba(255, 255, 255, 0.8);
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .cart thead {
            background-color: #111;
            color: #fff;
        }
        .cart th, .cart td {
            padding: 15px;
            text-align: center;
        }
        .cart tbody tr {
            border-bottom: 1px solid #ddd;
        }
        .cart tbody tr:hover {
            background-color: #f1f1f1;
        }
        .cart img {
            max-width: 100px;
            border-radius: 8px;
        }
        .cart .num {
            font-weight: bold;
        }
        .total {
            font-size: 1.2em;
            font-weight: bold;
            background-color: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .button {
            background-color: #00bbf9;
            color: #fff;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            margin: 10px 5px;
            display: inline-block;
        }
        .button:hover {
            background-color: #007bff;
        }
        .button.light {
            background-color: #f1f1f1;
            color: #000;
        }
        .button.light:hover {
            background-color: #ddd;
        }
    </style>
{% endblock %}